//=======================================================
//  This code is generated by Terasic System Builder
//  Modified for LSC: Digital Communication Lab (UNIFESP)
//=======================================================

module DE2_115_BluetoothSPP_Slave(
	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK_50,

	//////////// Sma //////////
	input 		          		SMA_CLKIN,
	output		          		SMA_CLKOUT,

	//////////// LED //////////
	output		     [8:0]		LEDG,
	output   		  [17:0]		LEDR,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// EX_IO //////////
	inout 		     [6:0]		EX_IO,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7,

	//////////// LCD //////////
	output		          		LCD_BLON,
	inout 		     [7:0]		LCD_DATA,
	output		          		LCD_EN,
	output		          		LCD_ON,
	output		          		LCD_RS,
	output		          		LCD_RW,

	//////////// RS232 //////////
	input 		          		UART_CTS,
	output		          		UART_RTS,
	input 		          		UART_RXD,
	output		          		UART_TXD,

	//////////// PS2 for Keyboard and Mouse //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2,

	//////////// SDCARD //////////
	output		          		SD_CLK,
	inout 		          		SD_CMD,
	inout 		     [3:0]		SD_DAT,
	input 		          		SD_WP_N,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// Audio //////////
	input 		          		AUD_ADCDAT,
	inout 		          		AUD_ADCLRCK,
	inout 		          		AUD_BCLK,
	output		          		AUD_DACDAT,
	inout 		          		AUD_DACLRCK,
	output		          		AUD_XCK,

	//////////// I2C for EEPROM //////////
	output		          		EEP_I2C_SCLK,
	inout 		          		EEP_I2C_SDAT,

	//////////// I2C for Audio Tv-Decoder  //////////
	output		          		I2C_SCLK,
	inout 		          		I2C_SDAT,

	//////////// Ethernet 0 //////////
	output		          		ENET0_GTX_CLK,
	input 		          		ENET0_INT_N,
	input 		          		ENET0_LINK100,
	output		          		ENET0_MDC,
	inout 		          		ENET0_MDIO,
	output		          		ENET0_RST_N,
	input 		          		ENET0_RX_CLK,
	input 		          		ENET0_RX_COL,
	input 		          		ENET0_RX_CRS,
	input 		     [3:0]		ENET0_RX_DATA,
	input 		          		ENET0_RX_DV,
	input 		          		ENET0_RX_ER,
	input 		          		ENET0_TX_CLK,
	output		     [3:0]		ENET0_TX_DATA,
	output		          		ENET0_TX_EN,
	output		          		ENET0_TX_ER,
	input 		          		ENETCLK_25,

	//////////// Ethernet 1 //////////
	output		          		ENET1_GTX_CLK,
	input 		          		ENET1_INT_N,
	input 		          		ENET1_LINK100,
	output		          		ENET1_MDC,
	inout 		          		ENET1_MDIO,
	output		          		ENET1_RST_N,
	input 		          		ENET1_RX_CLK,
	input 		          		ENET1_RX_COL,
	input 		          		ENET1_RX_CRS,
	input 		     [3:0]		ENET1_RX_DATA,
	input 		          		ENET1_RX_DV,
	input 		          		ENET1_RX_ER,
	input 		          		ENET1_TX_CLK,
	output		     [3:0]		ENET1_TX_DATA,
	output		          		ENET1_TX_EN,
	output		          		ENET1_TX_ER,

	//////////// TV Decoder //////////
	input 		          		TD_CLK27,
	input 		     [7:0]		TD_DATA,
	input 		          		TD_HS,
	output		          		TD_RESET_N,
	input 		          		TD_VS,

	//////////// USB 2.0 OTG (Cypress CY7C67200) //////////
	output		     [1:0]		OTG_ADDR,
	output		          		OTG_CS_N,
	inout 		    [15:0]		OTG_DATA,
	input 		          		OTG_INT,
	output		          		OTG_RD_N,
	output		          		OTG_RST_N,
	output		          		OTG_WE_N,

	//////////// IR Receiver //////////
	input 		          		IRDA_RXD,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [31:0]		DRAM_DQ,
	output		     [3:0]		DRAM_DQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_WE_N,

	//////////// SRAM //////////
	output		    [19:0]		SRAM_ADDR,
	output		          		SRAM_CE_N,
	inout 		    [15:0]		SRAM_DQ,
	output		          		SRAM_LB_N,
	output		          		SRAM_OE_N,
	output		          		SRAM_UB_N,
	output		          		SRAM_WE_N,

	//////////// Flash //////////
	output		    [22:0]		FL_ADDR,
	output		          		FL_CE_N,
	inout 		     [7:0]		FL_DQ,
	output		          		FL_OE_N,
	output		          		FL_RST_N,
	input 		          		FL_RY,
	output		          		FL_WE_N,
	output		          		FL_WP_N,

	//////////// GPIO, GPIO connect to RFS - RF and Sensor //////////
	inout 		          		BT_KEY,
	input 		          		BT_UART_RX,
	output		          		BT_UART_TX,
	input 		          		LSENSOR_INT,
	inout 		          		LSENSOR_SCL,
	inout 		          		LSENSOR_SDA,
	output		          		MPU_AD0_SDO,
	input		          			MPU_CS_n,
	output		          		MPU_FSYNC,
	input 		          		MPU_INT,
	inout 		          		MPU_SCL_SCLK,
	inout 		          		MPU_SDA_SDI,
	input 		          		RH_TEMP_DRDY_n,
	inout 		          		RH_TEMP_I2C_SCL,
	inout 		          		RH_TEMP_I2C_SDA,
	inout 		     [7:0]		TMD_D,
	input 		          		UART2USB_CTS,
	output		          		UART2USB_RTS,
	input 		          		UART2USB_RX,
	output		          		UART2USB_TX,
	output		          		WIFI_EN,
	output		          		WIFI_RST_n,
	input 		          		WIFI_UART0_CTS,
	output		          		WIFI_UART0_RTS,
	input 		          		WIFI_UART0_RX,
	output		          		WIFI_UART0_TX,
	input 		          		WIFI_UART1_RX
);

//=======================================================
//  REG/WIRE declarations
//=======================================================
assign  BT_UART_TX = txd;
assign  rxd  = BT_UART_RX;

wire 				rts; 
wire 				cts; 
wire 				rxd;
wire 				txd;
wire	 [7:0]   uart_data;
wire	         rdempty;
wire	         write;
reg	     	   read;
reg	         cnt;

wire [7:0] w_scan_code;
wire       w_keyboard_ready;

wire [1:0] w_sensor_sel;
wire [15:0] w_limiar_temp;
wire [15:0] w_limiar_umid;

// ======================================================
// 	THINGS OF THE PROJECT
// ======================================================
reg [2:0] 	state = 3'd0;
reg [2:0] 	prev_state = 3'd0;
reg [15:0] 	temp1_reg, temp2_reg;

reg [15:0] s1_min;
reg [15:0] s1_max;
reg [15:0] s2_min;
reg [15:0] s2_max;
reg        	alerta_reg;
reg		  	buzzer_reg;

// Parâmetros da FSM
localparam IDLE   = 3'd0,
           GET_T1_L = 3'd1,
           GET_T1_H = 3'd2,
           GET_T2_L = 3'd3,
           GET_T2_H = 3'd4,
           GET_BIN  = 3'd5;
			  
reg [29:0] watchdog_msg_cnt; 
reg conexao_viva;
reg state_timeout;
wire vga_pixel_clk, buzzer_wire;

//=======================================================
//  Structural coding
//=======================================================

// UART Controller
uart_control UART0(
	.clk(CLOCK_50),
	.reset_n(KEY[0]),
	.write(write),
	.writedata(uart_data),
	.read(read),
	.readdata(uart_data),
	.rdempty(rdempty),
	.uart_clk_25m(cnt),
	.uart_tx(txd),
	.uart_rx(rxd)
);	

//=======================================================
// 		MODULO PRINCIPAL (FSM CORRIGIDA)
//=======================================================
always @(posedge CLOCK_50 or negedge KEY[0]) begin
    if (!KEY[0]) begin
        state       <= IDLE;
        read        <= 0;
        temp1_reg   <= 0;
        temp2_reg   <= 0;
        alerta_reg  <= 0;
        buzzer_reg  <= 0;
        // Inicialização crítica para lógica de min/max estável
        s1_max      <= 16'd0;
        s1_min      <= 16'hFFFF; 
        s2_max      <= 16'd0;
        s2_min      <= 16'hFFFF;
    end else begin
        read <= 0;
		  
        if (!rdempty && !read) begin
            read <= 1; 
            
            case (state)
                IDLE: begin
                    if (uart_data == 8'hAA) // Header
                        state <= GET_T1_L;
                end
                
                GET_T1_L: begin
                    temp1_reg[7:0] <= uart_data;
                    state <= GET_T1_H;
                end
                
                GET_T1_H: begin
                    temp1_reg[15:8] <= uart_data;
                    state <= GET_T2_L;
                end
                
                GET_T2_L: begin
                    temp2_reg[7:0] <= uart_data;
                    state <= GET_T2_H;
                end
                
                GET_T2_H: begin
                    temp2_reg[15:8] <= uart_data;
                    state <= GET_BIN;
                end
                
                GET_BIN: begin
                    alerta_reg <= (uart_data == 8'd1);
                    state <= IDLE;
                    
                   // if (temp1_reg > w_limiar_temp) begin
                   //     buzzer_reg <= 1'b1; 
                   // end else begin
                   //     buzzer_reg <= 1'b0; 
                   // end

                    // Lógica robusta de Máximos e Mínimos Históricos
                    if (temp1_reg > s1_max) s1_max <= temp1_reg;
                    if (temp1_reg < s1_min) s1_min <= temp1_reg;
                    
                    if (temp2_reg > s2_max) s2_max <= temp2_reg;
                    if (temp2_reg < s2_min) s2_min <= temp2_reg;
                end
                
                default: state <= IDLE;
            endcase
        end
    end
end
assign buzzer_wire = ((temp1_reg > w_limiar_temp) || (temp2_reg > w_limiar_umid));
//=======================================================
// WATCHDOG
//=======================================================
always @(posedge CLOCK_50 or negedge KEY[0]) begin
    if (!KEY[0]) begin
        watchdog_msg_cnt <= 0;
        conexao_viva <= 0;
        state_timeout <= 0;
        prev_state <= IDLE;
    end else begin
        if (state == prev_state) begin
            watchdog_msg_cnt <= watchdog_msg_cnt + 1;
            if (watchdog_msg_cnt > 30'd2_000_000_000) begin
                state_timeout <= 1; 
            end
        end else begin
				prev_state <= state;
            watchdog_msg_cnt <= 0;
            state_timeout <= 0;
        end
    end
end

assign LEDG[8] = alerta_reg; 
assign MPU_AD0_SDO = buzzer_wire; 
assign LEDR[8] = state_timeout;

assign HEX6 = 7'hFF;
assign HEX7 = 7'hFF;
assign HEX5 = 7'hFF;
assign HEX4 = 7'hFF;
assign HEX3 = 7'hFF;

always@(posedge CLOCK_50)
	cnt <= cnt + 1;

//=======================================================
// INSTANCIAÇÃO DO VGA COMPATIBILIZADA
//=======================================================
vga_with_hw_test_image instancia_vga (
    .clk(CLOCK_50),           
    .t1_temp(temp1_reg),    
    .t2_temp(temp2_reg),    
    .sensor_selecionado(w_sensor_sel),
    .pixel_clk(VGA_CLK),      
    .h_sync(VGA_HS),          
    .v_sync(VGA_VS),          
    .n_blank(VGA_BLANK_N),    
    .n_sync(VGA_SYNC_N),      
    .blue(VGA_B),             
    .green(VGA_G),            
    .red(VGA_R),               
	 .alerta(alerta_reg),
	 .alerta_critico(buzzer_wire), 
	 .s1_max(s1_max),          // Agora mapeado dinamicamente para os registradores
	 .s1_min(s1_min),          
	 .s2_max(s2_max),          
	 .s2_min(s2_min)          
);

//=======================================================
// INTEGRACAO DO TECLADO PS/2 E CONTROLE DE LIMIARES
//=======================================================
ps2 u_teclado (
    .iCLK_50    (CLOCK_50),
    .iRST_n     (KEY[1]), 
    .PS2_CLK    (PS2_CLK),
    .PS2_DAT    (PS2_DAT),
    .oSCAN_CODE (w_scan_code),
    .oREADY     (w_keyboard_ready)
);

keyboard_controle u_controle (
    .iCLK_50      (CLOCK_50),
    .iRST_n       (KEY[1]),
    .iSCAN_CODE   (w_scan_code),
    .iKEY_READY   (w_keyboard_ready),
    .oSENSOR_SEL  (w_sensor_sel),
    .oLIMIAR_TEMP (w_limiar_temp),
    .oLIMIAR_UMID (w_limiar_umid)
);

reg [15:0] w_limiar_exibicao;
always @(*) begin
    if (w_sensor_sel == 2'b00)
        w_limiar_exibicao = w_limiar_temp/100;
    else
        w_limiar_exibicao = w_limiar_umid;
end
display_7seg u_display_(
    .data(w_limiar_exibicao), // 14 bits cobrem até 16383, suficiente para 4 dígitos (9999)
    .ligaOUT(1'b1),
    .unid_display(HEX0), .dez_display(HEX1), .cen_display(), .mil_display()
);
// SEG7_LUT u_display_hex0 (.oSEG(HEX0), .iDIG(w_limiar_exibicao[3:0]));
// SEG7_LUT u_display_hex1 (.oSEG(HEX1), .iDIG(w_limiar_exibicao[7:4]));
SEG7_LUT u_display_hex2 (.oSEG(HEX2), .iDIG({2'b00, w_sensor_sel})); 

endmodule